# Generated by Django 3.2.4 on 2021-07-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_auto_20210701_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_promotions', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('sale', models.CharField(max_length=5, verbose_name='Sale')),
                ('photo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Photo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
