# Generated by Django 3.2.4 on 2021-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotions_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='name_promotions_ru',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='name_promotions_uk',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
    ]
