# Generated by Django 3.2.4 on 2021-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20210813_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='name_promotions_ru',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='name_promotions_uk',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Назва'),
        ),
    ]
