# Generated by Django 3.2.4 on 2021-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20210813_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='slug',
            field=models.SlugField(default='', max_length=30, verbose_name='Part of the link'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Title'),
        ),
    ]
