# Generated by Django 3.2.4 on 2021-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20210817_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Part of the link'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
