# Generated by Django 3.2.4 on 2021-07-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'manager'), (2, 'editor'), (3, 'customer'), (4, 'wholesaler'), (5, 'retail wholesaler')], default=3, null=True),
        ),
    ]
