# Generated by Django 3.2.4 on 2021-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210712_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'manager'), (2, 'editor'), (3, 'customer'), (4, 'wholesaler'), (5, 'retail wholesaler'), (6, 'dropshipper')], default=3, null=True),
        ),
    ]
