# Generated by Django 3.2.4 on 2021-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'manager'), (2, 'editor'), (3, 'customer'), (4, 'wholesaler'), (5, 'retail wholesaler'), (6, 'dropshipper'), (7, 'admin')], default=3, null=True),
        ),
    ]
