# Generated by Django 3.2.4 on 2021-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('opt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Opt price')),
                ('small_opt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Small opt price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale price')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('status', models.IntegerField(choices=[(0, 'is available'), (1, 'not available'), (2, 'in order')], default=0, verbose_name='Status')),
            ],
        ),
    ]
