# Generated by Django 3.2.4 on 2021-07-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210705_1551'),
        ('attibutes', '0007_attributevariant_product'),
        ('vproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vproduct',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attibutes.attributevariant'),
        ),
        migrations.AddField(
            model_name='vproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
