# Generated by Django 3.2.4 on 2021-08-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vproduct', '0005_vproduct_drop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vproduct',
            name='description',
        ),
    ]
