# Generated by Django 3.2.4 on 2021-08-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img_news', verbose_name='Photo'),
        ),
    ]
