# Generated by Django 3.2.4 on 2021-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ru_post',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='news',
            name='ru_text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='news',
            name='uk_post',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='news',
            name='uk_text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
