# Generated by Django 3.2.4 on 2021-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210812_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ru_post',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ru_text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='uk_post',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='uk_text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
