# Generated by Django 3.2.4 on 2021-08-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_part_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='part_link',
            field=models.SlugField(default='', max_length=30, verbose_name='Part of the link'),
        ),
    ]
