# Generated by Django 3.2.4 on 2021-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_part_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='part_link',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Part of the link'),
        ),
    ]
