# Generated by Django 3.2.4 on 2021-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('model', models.CharField(max_length=30, unique=True, verbose_name='Model')),
                ('article', models.CharField(max_length=30, unique=True, verbose_name='Article')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('meta_description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta-description')),
                ('photo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Photo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('warehouse', models.IntegerField(default=0, verbose_name='Warehouse')),
                ('new', models.BooleanField(default=False, verbose_name='New')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('sex', models.IntegerField(choices=[(0, 'children'), (1, 'man'), (2, 'woman')], default=2, verbose_name='Sex')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, to='category.Category')),
                ('related_products', models.ManyToManyField(blank=True, related_name='_product_product_related_products_+', to='product.Product')),
            ],
        ),
    ]
