# Generated by Django 3.2.4 on 2021-06-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
        ('product', '0002_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.manufacturer'),
        ),
    ]
