# Generated by Django 3.2.4 on 2021-07-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0001_initial'),
        ('product', '0003_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attibutes.attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attibutes.attributesvalue'),
        ),
    ]
