# Generated by Django 3.2.4 on 2021-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0004_auto_20210701_1153'),
        ('product', '0004_auto_20210701_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='attibutes.Attributes'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes_value',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_value',
            field=models.ManyToManyField(blank=True, null=True, to='attibutes.AttributesValue'),
        ),
    ]
