# Generated by Django 3.2.4 on 2021-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210701_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='is_new',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_variability',
            field=models.BooleanField(default=False, verbose_name='Variability'),
        ),
        migrations.AddField(
            model_name='product',
            name='opt_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Opt price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale price'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_opt_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Small opt price'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'is available'), (1, 'not available'), (2, 'in order')], default=0, verbose_name='Status'),
        ),
    ]
