# Generated by Django 3.2.4 on 2021-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210701_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='v_product',
            field=models.ManyToManyField(blank=True, null=True, to='vproduct.VProduct'),
        ),
    ]
