# Generated by Django 3.2.4 on 2021-07-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_attribute_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='v_product',
        ),
    ]
