# Generated by Django 3.2.4 on 2021-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drop_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dropshipper price'),
        ),
    ]
