# Generated by Django 3.2.4 on 2021-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210813_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_link',
            field=models.SlugField(default='', max_length=30, verbose_name='Part of the link'),
        ),
    ]
