# Generated by Django 3.2.4 on 2021-07-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_category'),
        ('set', '0002_set_drop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='product.product'),
        ),
        migrations.AlterField(
            model_name='set',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='product.product'),
        ),
        migrations.AlterField(
            model_name='set',
            name='product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='product.product'),
        ),
        migrations.AlterField(
            model_name='set',
            name='product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='product.product'),
        ),
    ]
