# Generated by Django 3.2.4 on 2021-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0004_auto_20210720_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
