# Generated by Django 3.2.4 on 2021-07-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_alter_set_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='photo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Photo'),
        ),
    ]
