# Generated by Django 3.2.4 on 2021-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0006_alter_set_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='set_img', verbose_name='Photo'),
        ),
    ]
