# Generated by Django 3.2.4 on 2021-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0009_auto_20210817_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='set',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name_set_ru',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Название сета'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name_set_uk',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Назва сету'),
        ),
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Part of the link'),
        ),
        migrations.AlterField(
            model_name='set',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
