# Generated by Django 3.2.4 on 2021-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('avatar', models.CharField(max_length=130, null=True)),
                ('role', models.IntegerField(choices=[(1, 'customer'), (2, 'wholesaler')], default=1)),
            ],
        ),
    ]
