# Generated by Django 3.2.4 on 2021-07-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'wholesaler'), (3, 'retail wholesaler')], default=1),
        ),
    ]
