# Generated by Django 3.2.4 on 2021-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('photo', models.CharField(max_length=150, null=True, verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('parent_category', models.IntegerField(null=True, verbose_name='Parent category')),
                ('filters.py', models.CharField(max_length=50, verbose_name='Filter')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
