# Generated by Django 3.2.4 on 2021-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210705_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
