# Generated by Django 3.2.4 on 2021-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uk_description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='uk_name_category',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Назва'),
        ),
    ]
