# Generated by Django 3.2.4 on 2021-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20210811_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ru_description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='ru_name_category',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Назва'),
        ),
    ]
