# Generated by Django 3.2.4 on 2021-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210811_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='part_link',
            field=models.SlugField(default='', max_length=30, verbose_name='Part of the link'),
        ),
    ]
