# Generated by Django 3.2.4 on 2021-07-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviews_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
