# Generated by Django 3.2.4 on 2021-07-12 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=20, unique=True, verbose_name='Name company')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('logo', models.CharField(max_length=120, verbose_name='Logo')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('operating_mode', models.CharField(max_length=120, null=True, verbose_name='Operating mode')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
