# Generated by Django 3.2.4 on 2021-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ru_address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='ru_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='company',
            name='ru_name_company',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='ru_operating_mode',
            field=models.CharField(max_length=120, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='company',
            name='uk_address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='uk_description',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='company',
            name='uk_name_company',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='company',
            name='uk_operating_mode',
            field=models.CharField(max_length=120, null=True, verbose_name='Режим роботи'),
        ),
    ]
