# Generated by Django 3.2.4 on 2021-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesvalue',
            name='name_value',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
    ]
