# Generated by Django 3.2.4 on 2021-07-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0003_alter_attributesvalue_name_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='value',
        ),
        migrations.AddField(
            model_name='attributesvalue',
            name='name_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attibutes.attributes', verbose_name='Name attribute'),
        ),
    ]
