# Generated by Django 3.2.4 on 2021-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0004_auto_20210701_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='is_variability',
            field=models.BooleanField(default=False, verbose_name='Variability'),
        ),
    ]
