# Generated by Django 3.2.4 on 2021-07-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0005_attributes_is_variability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attibutes.attributes')),
                ('attribute_values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attibutes.attributesvalue')),
            ],
        ),
    ]
