# Generated by Django 3.2.4 on 2021-07-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0007_attributevariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevariant',
            name='attribute_v_name',
            field=models.CharField(default='www', max_length=30, verbose_name='Name'),
        ),
    ]
