# Generated by Django 3.2.4 on 2021-07-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0008_attributevariant_attribute_v_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesvalue',
            name='name_value',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name Value'),
        ),
        migrations.AlterField(
            model_name='attributevariant',
            name='attribute_v_name',
            field=models.CharField(default='www', max_length=30, verbose_name='Name Variant'),
        ),
    ]
