# Generated by Django 3.2.4 on 2021-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0009_auto_20210706_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevariant',
            name='attribute',
        ),
    ]
