# Generated by Django 3.2.4 on 2021-07-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vproduct', '0003_auto_20210706_1532'),
        ('product', '0009_auto_20210705_1551'),
        ('attibutes', '0010_remove_attributevariant_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesvalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='attributevariant',
            name='v_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vproduct.vproduct'),
        ),
    ]
