# Generated by Django 3.2.4 on 2021-07-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210705_1551'),
        ('attibutes', '0012_remove_attributevariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesvalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='product.product'),
        ),
    ]
