# Generated by Django 3.2.4 on 2021-07-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vproduct', '0005_vproduct_drop_price'),
        ('attibutes', '0013_alter_attributesvalue_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='is_variability',
        ),
        migrations.AddField(
            model_name='attributesvalue',
            name='is_variability',
            field=models.BooleanField(default=False, verbose_name='Variability'),
        ),
        migrations.AddField(
            model_name='attributesvalue',
            name='v_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vproduct.vproduct'),
        ),
        migrations.DeleteModel(
            name='AttributeVariant',
        ),
    ]
