# Generated by Django 3.2.4 on 2021-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attibutes', '0015_remove_attributesvalue_is_variability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesvalue',
            name='name_value',
            field=models.CharField(max_length=20, verbose_name='Name Value'),
        ),
    ]
