# Generated by Django 3.2.4 on 2021-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='summa',
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='is_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
