# Generated by Django 3.2.4 on 2021-07-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210722_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='is_confirmation',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'in processing'), (2, 'accepted'), (3, 'on maintenance'), (4, 'sent'), (5, 'done'), (6, 'canceled'), (7, 'deleted')], default=1)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('type_payment', models.IntegerField(choices=[(1, 'to a bank card'), (2, 'C. O. D.')], default=2)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
            ],
        ),
    ]
