# Generated by Django 3.2.4 on 2021-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20210722_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='basket.Basket'),
        ),
    ]
