# Generated by Django 3.2.4 on 2021-07-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vproduct', '0005_vproduct_drop_price'),
        ('basket', '0010_basket_vproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='vproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vproduct.vproduct'),
        ),
    ]
