# Generated by Django 3.2.4 on 2021-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_selection_vproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.IntegerField(choices=[(1, 'в процессе'), (2, 'принято'), (3, 'в обработке'), (4, 'отправлено'), (5, 'сделано'), (6, 'отменен'), (7, 'удалено')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uk',
            field=models.IntegerField(choices=[(1, 'в процесі'), (2, 'прийнято'), (3, 'в обробці'), (4, 'відправлено'), (5, 'зроблено'), (6, 'скасовано'), (7, 'видалено')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='type_payment_ru',
            field=models.IntegerField(choices=[(1, 'на банковскую карту'), (2, 'наложный платеж')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='type_payment_uk',
            field=models.IntegerField(choices=[(1, 'на банківську картку'), (2, 'акладний платіж')], default=2),
        ),
    ]
